### ISSUE TITLE
Problems compiling

### ISSUE THREAD

**Issue by pablobuenob** [marcofaltelli/Metronome#1]
I am trying to compile the hr_sleep module with sleep but i get this problems: 

/home/pablo/Metronome-main/hr_sleep/./lib/vtpmo.c: In function ‘sys_vtpmo’:
/home/pablo/Metronome-main/hr_sleep/./lib/vtpmo.c:58:28: error: implicit declaration of function ‘phys_to_virt’; did you mean ‘page_to_virt’? [-Werror=implicit-function-declaration]
   58 | #define PAGE_TABLE_ADDRESS phys_to_virt(_read_cr3() & ADDRESS_MASK)
      |                            ^~~~~~~~~~~~
/home/pablo/Metronome-main/hr_sleep/./lib/vtpmo.c:102:17: note: in expansion of macro ‘PAGE_TABLE_ADDRESS’
  102 |         pml4  = PAGE_TABLE_ADDRESS;
      |                 ^~~~~~~~~~~~~~~~~~
/home/pablo/Metronome-main/hr_sleep/./lib/vtpmo.c:102:15: warning: assignment to ‘pgd_t *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  102 |         pml4  = PAGE_TABLE_ADDRESS;
      |               ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:297: /home/pablo/Metronome-main/hr_sleep/./lib/vtpmo.o] Error 1
make[1]: *** [Makefile:1907: /home/pablo/Metronome-main/hr_sleep] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-71-generic'
make: *** [Makefile:5: all] Error 2

What can i do to solve this problem?

Regards

**Comment by marcofaltelli** [comment]
Hi!
Thank you for your comment; the module should now be updated to the newer kernel requirements.
Please pull the latest commit and let me know if this is solved.
